# Generated by Django 3.2.16 on 2022-10-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('typeID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weekly_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('late_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('change_branch_fee', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
