# Generated by Django 3.2.16 on 2022-10-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_car_car_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchID', models.AutoField(primary_key=True, serialize=False)),
                ('branch_phone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('street_number', models.CharField(max_length=30)),
                ('street_name', models.CharField(max_length=30)),
                ('unit_number', models.CharField(max_length=30)),
            ],
        ),
    ]
