# Generated by Django 3.2.16 on 2022-10-28 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='goldMember',
            new_name='gold_member',
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rentalID', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('date_returned', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gold_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('license_plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.car')),
            ],
        ),
    ]
