# Generated by Django 3.2.16 on 2022-10-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221027_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('employee_phone', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rank', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('street_number', models.CharField(max_length=30)),
                ('street_name', models.CharField(max_length=30)),
                ('unit_number', models.CharField(max_length=30)),
                ('branchID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
    ]
