# Generated by Django 3.2.16 on 2022-10-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='unit_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
