# Generated by Django 4.1.2 on 2022-10-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_employee_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='unit_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
