# Generated by Django 4.1.2 on 2022-10-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_branch_unit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='eID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
