# Generated by Django 4.1.2 on 2022-10-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rental_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='branchID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
    ]
