# Generated by Django 4.1.2 on 2022-10-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_car_branchid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='gold_member',
        ),
        migrations.AddField(
            model_name='rental',
            name='cID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
    ]
